services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.win
    env_file:
      - .env
    environment:
      MEDIA_ROOT: C:\app\static\uploads
    ports:
      - "443:8000"
    volumes:
      - C:\whatsapp_api\static\uploads:C:\app\static\uploads
    restart: unless-stopped
    isolation: hyperv
