services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.win
    env_file:
      - .env
    environment:
      # Ruta interna del contenedor donde se guardan las imágenes
      MEDIA_ROOT: /app/static/uploads
    ports:
      - "443:8000"
    volumes:
      # Ruta en Windows  -> ruta dentro del contenedor
      - "C:\\whatsapp_api\\media_uploads:/app/static/uploads"
    restart: unless-stopped
    isolation: hyperv
